[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "views"

[functions]
  external_node_modules = ["express", "ejs", "sequelize", "body-parser"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
  force = true